#!/usr/bin/env bash
# Thiz script gives you information about the school file

if test  -e "school"
	then 
		echo "school file exists"
		if [ -s "school"] 
		then 
			echo "school file is empty"
		else 
			echo "school file is not empty"
		
		if test -f "school"
		then 
			echo "school is a regular file"
	
else 
       echo "school file does not exists"

      
