#!/usr/bin/env bash
# 

sudo ./tmp/my_process &
if [ "${1}" == "start" ]
then
	start "manage_my_process" ./tmp/my_process & 
	touch /var/run/my_process.pid
	echo "manage_my_process started"

   elif [ "${1}" == "stop" ]
   then
	stop "manage_my_process" ./tmp/my_process &
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"

	
   elif [ "${1}" == "restart" ]
   then
	stop "manage_my_process" ./tmp/my_process &
	rm /var/run/my_process.pid
	start "manage_my_process"
	touch /var/run/my_process.pid
	echo "manage_my_process restarted"
	
   else
	echo "Usage: manage_my_process {start|stop|restart}"
fi


